# SPDX-License-Identifier: GPL-2.0

ARCH?=arm64
LRH_ARCH?=aarch64

TECHPACK_BINDING_DIR=$(PWD)
TECHPACK_DTSTREE=$(TECHPACK_BINDING_DIR)

KDIR ?= $(SRC_DIR_ROOT)/kernel/kernel_platform/kernel

BASE_DTB_IN ?= $(KDIR)/arch/arm64/boot/dts/qcom
DTB_MERGE_OUT ?= $(KDIR)/arch/arm64/boot/dts/qcom

#Include the paths for DT binding header files. First two are standard paths
# found in mainline kernel. Post that, add any paths for module specific, out
# of tree definition of the device tree bindings. Here, last two paths contain
# the out of tree device tree bindings.
TECHPACK_INCLUDE := $(KDIR)/scripts/dtc/include-prefixes
TECHPACK_INCLUDE += $(KDIR)/include
TECHPACK_INCLUDE += $(KDIR)/arch/$(ARCH)/boot/dts/qcom
TECHPACK_INCLUDE += $(TECHPACK_BINDING_DIR)
TECHPACK_INCLUDE += $(TECHPACK_BINDING_DIR)/oot-dt-bindings

SUB_TECH_BUILD:=$(wildcard techpacks/*/build.sh)

all: dtbos

dtbos:
	$(MAKE) -C $(KDIR) ARCH=$(ARCH) dtstree=$(TECHPACK_DTSTREE) \
		DTC_INCLUDE="$(TECHPACK_INCLUDE)" DTC_FLAGS="-@" dtbs

.PHONY: clean
clean:
	find  \( -name ".*.cmd" -o -name ".*.tmp" -o -name "*.dtb"  -o -name "*.dtbo" \) -delete
	rm -rf oot
